### PR TITLE
Remove .npy binaries from history

### PR DESCRIPTION
**Pull request by janEbert**
Hi, not sure if this works as a PR since it's about rewriting the repo history. I've removed the binary files which bloat the repo's size using [git-filter-repo](https://github.com/newren/git-filter-repo):
```sh
git filter-repo --invert-paths --path-glob 'src/gpt/pretrain/*.npy'
```

This decreases the fully cloned repository's size from 417 MB to 3.2 MB.
Please also be sure whether it's a good idea – I'm not a maintainer of OSS that others rely on and have no idea how this interacts with Registrator.jl. Everybody developing on this repo would have to manually rebase onto the new master using `git rebase origin/master`, as far as I understand. Currently, only CompatHelper PRs and my GPT2 PR are open so it might be a good time to do it when those are merged?

Some links discouraging what I did:
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#The-Nuclear-Option:-filter-branch
https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#Removing-Objects
https://git-scm.com/docs/git-rebase#_recovering_from_upstream_rebase

### CODE REVIEW

**Comment by chengchingwen** [comment]
It's a little weird because I remember I did the same thing around July this year. Could you try cloning the repo again and see if there are still anything more than 5Mb?

**Comment by janEbert** [comment]
I did a fresh clone for comparing the numbers. Maybe you could try it as well? I had also ran `git gc --aggressive` on the repo some time before which didn't remove the files from the Git data.
Or could there be some system-wide Git cache on my end that does not properly update the branch?

**Comment by chengchingwen** [comment]
I also did a fresh clone and get a 415Mb git data downloaded, while my regular working directory only contain 5Mb git data. So looks like my previous attempt failed to clean the git data on GitHub's server. I'll try to figure out how can we get rid of those files safely.

**Comment by chengchingwen** [comment]
@janEbert  I figure it out. GitHub keep the old git tree since they were tagged. I have re-tagged them and this problem should be gone.

**Comment by janEbert** [comment]
Great to know what the issue was! Thanks :)

**Pull request closed without merging**
